[2025-05-05T12:00:44.070+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T11:45:00+00:00 [queued]>
[2025-05-05T12:00:44.147+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T11:45:00+00:00 [queued]>
[2025-05-05T12:00:44.151+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-05T12:00:44.582+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-05 11:45:00+00:00
[2025-05-05T12:00:45.566+0000] {standard_task_runner.py:60} INFO - Started process 433 to run task
[2025-05-05T12:00:46.024+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-05T11:45:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpzm9plo2r']
[2025-05-05T12:00:46.131+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask fetch_velib_data
[2025-05-05T12:00:51.099+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T11:45:00+00:00 [running]> on host b689fc3f3fb2
[2025-05-05T12:00:56.671+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T11:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-05T11:45:00+00:00'
[2025-05-05T12:00:56.695+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T12:00:56.799+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-05T12:00:56.860+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T12:01:10.374+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données
[2025-05-05T12:01:10.934+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T12:01:14.624+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250505T114500, start_date=20250505T120044, end_date=20250505T120114
[2025-05-05T12:01:14.732+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-05T12:01:15.412+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
