[2025-05-06T10:15:06.467+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T10:00:00+00:00 [queued]>
[2025-05-06T10:15:06.496+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T10:00:00+00:00 [queued]>
[2025-05-06T10:15:06.498+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-06T10:15:06.559+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-06 10:00:00+00:00
[2025-05-06T10:15:06.578+0000] {standard_task_runner.py:60} INFO - Started process 790 to run task
[2025-05-06T10:15:06.647+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-06T10:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmp1r7nz8gz']
[2025-05-06T10:15:06.670+0000] {standard_task_runner.py:88} INFO - Job 125: Subtask fetch_velib_data
[2025-05-06T10:15:07.847+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T10:00:00+00:00 [running]> on host 5fdd72692c9b
[2025-05-06T10:15:09.255+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-06T10:00:00+00:00'
[2025-05-06T10:15:09.260+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T10:15:09.271+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-06T10:15:09.290+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T10:15:15.280+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données
[2025-05-06T10:15:15.804+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-06T10:15:16.316+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250506T100000, start_date=20250506T101506, end_date=20250506T101516
[2025-05-06T10:15:16.404+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-06T10:15:16.734+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
