[2025-05-05T10:30:06.836+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T10:15:00+00:00 [queued]>
[2025-05-05T10:30:06.854+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T10:15:00+00:00 [queued]>
[2025-05-05T10:30:06.855+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-05T10:30:06.888+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-05 10:15:00+00:00
[2025-05-05T10:30:06.893+0000] {standard_task_runner.py:60} INFO - Started process 468 to run task
[2025-05-05T10:30:06.898+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-05T10:15:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpfo_ti3zx']
[2025-05-05T10:30:06.902+0000] {standard_task_runner.py:88} INFO - Job 75: Subtask fetch_velib_data
[2025-05-05T10:30:07.726+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T10:15:00+00:00 [running]> on host 6e22c01489ce
[2025-05-05T10:30:08.547+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T10:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-05T10:15:00+00:00'
[2025-05-05T10:30:08.550+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T10:30:08.552+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-05T10:30:08.565+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T10:30:10.464+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données
[2025-05-05T10:30:10.590+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T10:30:10.935+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250505T101500, start_date=20250505T103006, end_date=20250505T103010
[2025-05-05T10:30:11.014+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-05T10:30:11.289+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
