[2025-05-05T14:15:18.270+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T14:00:00+00:00 [queued]>
[2025-05-05T14:15:18.336+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T14:00:00+00:00 [queued]>
[2025-05-05T14:15:18.339+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-05T14:15:18.442+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-05 14:00:00+00:00
[2025-05-05T14:15:18.463+0000] {standard_task_runner.py:60} INFO - Started process 1002 to run task
[2025-05-05T14:15:18.479+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-05T14:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmp521rlce4']
[2025-05-05T14:15:18.495+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask fetch_velib_data
[2025-05-05T14:15:21.080+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T14:00:00+00:00 [running]> on host b689fc3f3fb2
[2025-05-05T14:15:24.084+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-05T14:00:00+00:00'
[2025-05-05T14:15:24.093+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T14:15:24.106+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-05T14:15:24.142+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T14:15:31.606+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données
[2025-05-05T14:15:32.121+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T14:15:33.259+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250505T140000, start_date=20250505T141518, end_date=20250505T141533
[2025-05-05T14:15:33.413+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-05T14:15:34.392+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
